name: first_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  intl: ^0.15.8
  cupertino_icons: ^0.1.2
  dio: ^3.0.3
  dio_cookie_manager: ^1.0.0
  provider: ^3.0.0+1
  image_picker: ^0.6.0+20
  geolocator: ^5.1.1+1
  camera: ^0.5.2+2
  path_provider: ^1.2.0
  video_player: ^0.10.1+6
  webview_flutter: ^0.3.10+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.2


flutter:

  uses-material-design: true

  assets:
    - imgs/avatar.png
